---
infra:
    provision:
      cloud:
        aws:
          ami: ami-0b00212ef9a4711c6
          region: us-east-1d
          security_groups:
          - default
          instance_type: m1-large
          instances:
          - name: db_server
            region: us-east-2
          - name: host19
          - name: host2
            ami: ami-0b00212ef9a4711c6
            count: 4
            instance_type: m1-large

    #   baremetal:
    #     beaker:
    #       arch: x86_64
    #       distro: RHEL-7.4
    #       variant: Server
    #       hostrequires:
    #         - tag: processor
    #           op: ">="
    #           value: 4
    #         - tag: device
    #           op: "="
    #           type: network
    #       job_group: central-ci-ops
    #
    #       instances:
    #       - name: foo1
    #         arch: s390x
    #         keyvalue:
    #           network: e1000
    #       - name: foo2
    #         arch: aarm64
    #       - name: foo3
    #         variant: Workstation
    #
    # configure:
#
#      openstack:
#        count: 2

#    - baremetal:
#      - type: "beaker"
#        count: 2
#        distro: "rhel"
#        arch: "x86_64"
#        variant: "server"
#
#    - container:
#        count: 3
#        name: "mysql"
#        type: "docker"
#
#  - configure:
#    - playbook:
#        location: /home/runtest.yml
#        params: 'version=3.7'
#
#tests:
#  - playbook:
#      location: /home/runtest.yml
#      params: 'version=3.7'
#
#results:
#  - format:
#    - xunit:
#      location: /path/to/output/
#      file_names:
#        - ouptut.xml
#        - errors.xml
#    - artifacts:
#      location: /path/for/artifact/storage/
#      file_names: "*"
#
#  - delivery:
#    - email:
#        addresses:
#          - you@example.com
#          - me@example.com
#    - messaging:
#        - irc:
#          server: irc.foo.com
#          channel: "#yipee"
#          message: "Run completed successfully"
#        - umb:
#          topic: "thisIsMyTopic"
#          message: "This is my message"
