---
- hosts: aws
  remote_user: ec2-user
  become: yes
  become_user: root

  tasks:
  - name: install the latest fortune package
    yum:
      name: fortune
      state: latest
  - name: execute fortune
    command: fortune
